src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/ProjectExtensions.cs, test/VSSDK.TestExtension/Commands/BuildActiveProjectAsyncCommand.cs, test/VSSDK.TestExtension/TestExtensionPackage.cs, test/VSSDK.TestExtension/VSCommandTable.cs, test/VSSDK.TestExtension/VSCommandTable.vsct, test/VSSDK.TestExtension/VSSDK.TestExtension.csproj
This PR adds a new extension method that allows building a project asynchronously and returns the build result as a `bool`.  To test this I have also added a new main menu and group that can be used for testing this and a good place for future commands for testing: 
If this is deemed useful I can also look at doing something similar for the solution.
=> Build a project asynchronously

src/Community.VisualStudio.Toolkit.Shared/ToolWindows/BaseToolWindow.cs
While playing around with an extension and the toolkit I noticed that my command didn't open my tool window, and I soon found it was because I forgot the `ProvideToolWindow` attribute on the package. But new extenders may not realize this so quickly so I thought it would be useful to provide some feedback rather than silently failing.
This pull request modifies `BaseToolWindow<T>.Initialize` so that it throws if the package doesn't have a corresponding `ProvideToolWindow` attribute set for the tool window's Pane.
I also added a Debug.Fail but that will only fire for developers testing the toolkit itself -- not for users of the release-built nuget package.
=> Verify that the package has a ProvideToolWindow attribute

src/Community.VisualStudio.Toolkit.14.0/Community.VisualStudio.Toolkit.14.0.csproj, src/Community.VisualStudio.Toolkit.16.0/Community.VisualStudio.Toolkit.16.0.csproj, src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/IVsHierarchyExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/IVsShareAssetsProjectExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/IVsSolutionExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/ProjectExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems
These are some methods I've found useful and wanted to see if it made sense to add them here as well.  This PR adds the following extension methods:
* `IVsHierarchy.IsSdkStyleProject` - returns whether the hierarchy is a newer SDK style project or not
* `IVsHierarchy.IsSharedProject` - returns whether the hierarchy is a shared project or not
* `IVsHierarchy.GetSharedAssetsProject` - returns the `IVsSharedAssetsProject` object for the shared project
* `IVsSharedAssetsProject.GetReferencingHierarchies` - returns a collection of projects that reference the shared project
* `Project.ToHierarchyAsync` - returns the `IVsHierarchy` for the project
* `Project.GetProjectIdAsync` - returns the guid for the project as identified in the solution
* `Project.IsSdkStyleProjectAsync` - returns whether …
=> Added extension methods around projects and hierarchies.

Community.VisualStudio.Toolkit.sln, src/Common.props, src/Community.VisualStudio.Toolkit.targets
From this discussion: https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/discussions/13
This is the build target part. I'll leave this PR as a draft until the extension is written, which I aim to do this weekend. 🥳 
* There are four different message levels that can be specified in the `ExtensibilityEssentialsLevel` build property:
* `None` disables it.
* `Info` (the default) produces a message.
* `Warning` produces a build warning.
* `Error` produces a build error.
* Any other value will produce a build warning telling you that the value is invalid.
* In Visual Studio 2019 (16.8+), the clickable link in the error list for _warnings and errors_ will take you to the marketplace page for the extension.
* For messages (the `Info` level), it's not possible to specify a link at …
=> Created build target to check for presence of the Extensibility Essentials extension

src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/SolutionExtensions.cs
These are certainly not ground breaking... the `SaveAsync` at least simplifies it for newcomers (don't need to pass in the name of the solution).  Really this is more about setting forth what the "ideal" would be which is to have an async version of being able to save the solution.  This at least brings that to the forefront as well as ensures that for now it's being handled properly by executing on the UI thread.
=> Added extension methods for saving the solution.

src/Community.VisualStudio.Toolkit.Shared/ToolkitThreadHelper.cs, src/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems, test/VSSDK.TestExtension/MEF/TextviewCreationListener.cs, test/VSSDK.TestExtension/VSSDK.TestExtension.csproj, test/VSSDK.TestExtension/source.extension.vsixmanifest
Added:
- ToolkitThreadHelper.cs in Toolkit.Shared
- TextviewCreationListener.cs in the TestExtension 
`ToolkitThreadHelper` provides a `JoinableTaskFactory` that is safe to use in MEF components or when an `AsyncPackage.JoinableTaskFactory` is not available.
Usage example:
```
[Export(typeof(IWpfTextViewCreationListener))]
[ContentType("text")]
[TextViewRole(PredefinedTextViewRoles.PrimaryDocument)]
internal class TextviewCreationListener : IWpfTextViewCreationListener, IDisposable
{
private readonly ToolkitThreadHelper _threadHelper = new ToolkitThreadHelper(ThreadHelper.JoinableTaskContext);
public void Dispose()
{
Dispose(true);
GC.SuppressFinalize(this);
}
protected virtual void Dispose(bool disposing)
{
if (disposing)
{
_threadHelper.Dispose();
}
}
public void …
```
=> ToolkitThreadHelper - a safe JoinableTaskFactory for MEF components (and other cases where package JTF not available)

src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/TaskExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/ToolkitThreadHelper.cs, test/VSSDK.TestExtension/MEF/TextviewCreationListener.cs, test/VSSDK.TestExtension/VSSDK.TestExtension.csproj
Changes after code review:
* New ForgetAndLogOnFailure(JoinableTask) overload
* Replaced ToolkitThreadHelper ctor with two static factory methods
* TextViewCreationListener (example of how to use new ToolkitThreadHelper) now uses ForgetAndLogOnFailure
* Fixed TextViewCreationListener case
=> Changes to ToolkitThreadHelper & TextViewCreationListener and new ForgetAndLogOnFailure overload for JoinableTask

src/Community.VisualStudio.Toolkit.Shared/Helpers/OutputWindowPane.cs, src/Community.VisualStudio.Toolkit.Shared/Helpers/OutputWindowTextWriterVS14.cs, src/Community.VisualStudio.Toolkit.Shared/Services/Windows.cs, src/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems
`OutputWindowPane` allows an extension to create a new Output window pane or get an existing one.
A pane can be activated (shown), hidden and cleared. Text can be written to the pane via methods like `WriteLineAsync` or with a `TextWriter` returned from `CreateOutputPaneTextWriterAsync`. (For newer versions of VS, this uses [OutputWindowTextWriter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.outputwindowtextwriter?view=visualstudiosdk-2019) from the SDK.)
Examples:
```
OutputWindowPane generalPane = await VS.Windows.GetOutputWindowPaneAsync(VSOutputWindowPane.General);
OutputWindowPane buildPane = await VS.Windows.GetOutputWindowPaneAsync(VSOutputWindowPane.Build);
OutputWindowPane debugPane = await VS.Windows.GetOutputWindowPaneAsync(VSOutputWindowPane.Debug); …
```
=> OutputWindowPane

src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/ExceptionExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/Helpers/OutputWindowPane.cs
`LogAsync` in `ExceptionExtensions` now uses the new `OutputWindowPane`.
=> Updated ExceptionExtensions to use new OutputWindowPane.

src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/ExceptionExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/Helpers/OutputWindowPane.cs, src/Community.VisualStudio.Toolkit.Shared/Services/Windows.cs
Without this change, the following code would return an empty Name:
```
OutputWindowPane pane = await VS.Windows.CreateOutputWindowPaneAsync("My Pane");
myPaneGuid = pane.Guid;
// Elsewhere:
OutputWindowPane myPane = await VS.Windows.GetOutputWindowPaneAsync(myPaneGuid);
Debug.Assert(myPane.Name == "My Pane"); // False! This would be empty
```
Previously:
```
async Task GetOrCreateAsync()
{
try
{
await VS.Windows.GetOutputWindowPaneAsync(myPaneGuid);
}
finally
{
await VS.Windows.CreateOutputWindowPaneAsync("My Pane");
}
}
```
Now:
```
async Task GetOrCreateAsync()
{
if (await VS.Windows.GetOutputWindowPaneAsync(myPaneGuid) == null)
{
await VS.Windows.CreateOutputWindowPaneAsync("My Pane");
}
}
```
=> Some improvements to OutputWindowPane

src/Community.VisualStudio.Toolkit.Shared/Commands/Commanding.cs, src/Community.VisualStudio.Toolkit.Shared/Editor/Editor.cs, src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/ImageMonikerExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/ProjectExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/Helpers/OutputWindowPane.cs, src/Community.VisualStudio.Toolkit.Shared/Notifications/Notifications.cs, src/Community.VisualStudio.Toolkit.Shared/Notifications/Statusbar.cs, src/Community.VisualStudio.Toolkit.Shared/Options/BaseOptionModel.cs, src/Community.VisualStudio.Toolkit.Shared/Services/Debugger.cs, src/Community.VisualStudio.Toolkit.Shared/Services/Shell.cs, src/Community.VisualStudio.Toolkit.Shared/Services/Solution.cs, src/Community.VisualStudio.Toolkit.Shared/Services/Windows.cs, src/Community.VisualStudio.Toolkit.Shared/VS.cs
Based on the XML comments for the `VS.GetServiceAsync` method, it should return `null` if the service is not found... but that's not true. The `Assumes.Present` method will throw an exception if the service is not found. This PR removes that line and creates a new `VS.GetRequiredServiceAsync` method which does perform that logic and follows the current pattern of the `System.IServiceProvider` naming conventions.
=> Added new 'GetRequiredServiceAsync' method.

src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/WindowExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/Services/Windows.cs, src/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems
Per the [documentation](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-and-managing-modal-dialog-boxes?view=vs-2019), showing a dialog window properly takes a little more code than just `window.ShowDialog`.  This PR encapsulates that logic in an extension method and also a helper method on the `VS.Windows` class.
=> Added the ability to show a 'System.Windows.Window' as a dialog.

src/Community.VisualStudio.Toolkit.Shared/Themes/Themes.cs, test/VSSDK.TestExtension/ToolWindows/ThemeWindowDemo.xaml
Fixes #57.
`EnvironmentColors.StartPageTextBodyBrushKey` looked OK when using the dark theme, but it was basically white when using the light and blue themes, so it's not a suitable foreground color.
I've change the foreground color to use `ThemedDialogColors.WindowPanelTextBrushKey`, which appears to be what the `Label` uses:
(light, blue and dark themes from top to bottom).
To match this change, I've also changed the background color to `ThemedDialogColors.WindowPanelBrushKey`. This _does_ make the background slightly darker for the light and blue themes. The dark theme appears to be the same color.
Before:
After:
=> Fixed foreground and background colors for theming

src/Community.VisualStudio.Toolkit.Shared/ToolWindows/BaseToolWindow.cs, test/VSSDK.TestExtension/ToolWindows/MultiInstanceWindow.cs, test/VSSDK.TestExtension/ToolWindows/RunnerWindow.cs, test/VSSDK.TestExtension/ToolWindows/ThemeWindow.cs
When FxCop/NetAnalyzers are enabled, the nested `public class Pane` causes warning `CA1034: Nested types should not be visible`
This change is mainly for the benefit of people copying these samples, since these analyzers are not enabled in the Toolkit itself.
=> Change tool window nested Pane classes to internal instead of public

src/Community.VisualStudio.Toolkit.Shared/Commands/BaseCommand.cs
`BaseCommand.Command` and `BaseCommand.Package` can't be initialized when the object is created, but for all intents and purposes, those two properties are non-null because they are set immediately after the object is created in `BaseCommand.InitializeAsync()`.
For a consumer, needing to use the null-conditional operator for a property that will always be non-null is annoying, so it's best to declare them as non-nullable.
I'm not sure what the preferred way to do this is. I initially wrapped the properties in `#nullable disable`/`#nullable restore`, but decided to instead initialize them to `null!` (using the null-forgiving operator). I'm happy to go with whatever the recommended way is. 😄
=> BaseCommand's Command and Package are always non-null

src/Community.VisualStudio.Toolkit.Shared/Selection/Selection.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/File.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/Project.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/SolutionFolder.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/Solutions.cs
- Removed various nullable reference type variable declarations when not needed
- Moved a memory allocation outside of a loop in order to reuse it
- Fixed what I think is a bug in `SolutionFolder.TryRemoveAsync` where it was comparing the HRESULT with a literal 1 instead of `VSConstants.S_OK` (0).
=> Small Improvements

src/Community.VisualStudio.Toolkit.Shared/Commands/Commands.cs, src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/CommandExtensions.cs
`CommandExtensions.ExecuteAsync` now calculates the required byte size of the input string argument. This was previously hard-coded as 200 bytes.
=> Improved CommandExtensions.ExecuteAsync

src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/IVsHierarchyExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/IVsSolutionExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/Notifications/MessageBox.cs, src/Community.VisualStudio.Toolkit.Shared/Selection/Selection.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/SolutionItem.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/Solutions.cs
This fixes #107 (for the most part).  There are some other scenarios I noticed, but can be done in a future issue/PR.  For example, selecting multiple items under a project's Analyzers don't appear to return correctly.
This also updated some misspellings and found line variables swapped when showing a message box.
=> Add selected solution item to GetSelectedItemsAsync()

src/Community.VisualStudio.Toolkit.Shared/Selection/Selection.cs
Closes #109 
I believe @shaggygi's refactoring to use `results.Distinct` was to keep the previous logic of
```
if (hierItem != null && !results.Contains(hierItem))
```
But based on the discussion in #109 I don't think this is needed.
=> Remove results.Distinct()

Community.VisualStudio.Toolkit.sln, src/Community.VisualStudio.Toolkit.Shared/Options/BaseOptionModel.cs, src/Community.VisualStudio.Toolkit.Shared/Options/IOptionModelPropertyWrapper.cs, src/Community.VisualStudio.Toolkit.Shared/Options/NativeSettingsType.cs, src/Community.VisualStudio.Toolkit.Shared/Options/OptionModelPropertyWrapper.cs, src/Community.VisualStudio.Toolkit.Shared/Options/OverrideCollectionNameAttribute.cs, src/Community.VisualStudio.Toolkit.Shared/Options/OverrideDataTypeAttribute.cs, src/Community.VisualStudio.Toolkit.Shared/Options/OverridePropertyNameAttribute.cs, src/Community.VisualStudio.Toolkit.Shared/Options/SettingDataType.cs, src/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems, src/Community.VisualStudio.Toolkit.UnitTests/App.config, src/Community.VisualStudio.Toolkit.UnitTests/Community.VisualStudio.Toolkit.UnitTests.csproj, src/Community.VisualStudio.Toolkit.UnitTests/OptionModelPropertyWrapperTests.cs, test/VSSDK.TestExtension/Options/General.cs
- Types supported: [Integral numeric types except for nint and nuint](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types), all enumeration types (via underlying type), bool, float, double, decimal, char, string, DateTime, DateTimeOffset, Color, and Guid.
- Types with caveats: string (null becomes string.empty), byte[] and MemoryStream which if null become empty byte arrays.
- Special Handling: Color, Guid, DateTime, DateTimeOffset, float, and double are handled specially to assure they round-trip. Convert.ChangeType is used for the remainder of the types, if the type is not already an exact match for the settings store.
- For other types, for example string[], the default serialization is now using XmlSerializer rather than …
=> BaseOptionModel serializes to the closest data type by default (#112)

src/Community.VisualStudio.Toolkit.Shared/Themes/ThemeResources.xaml, src/Community.VisualStudio.Toolkit.Shared/Themes/ToolkitResourceKeys.cs, test/VSSDK.TestExtension/ToolWindows/ThemeWindow/ThemeWindowDemo.xaml, test/VSSDK.TestExtension/ToolWindows/ThemeWindow/ThemeWindowDemo.xaml.cs
Relates to #106.
There's a `Microsoft.VisualStudio.PlatformUI.SmoothProgressBar` which is already themed, so it seems like a better choice than a regular `ProgressBar`. No theming is needed, but the default height is thin (similar to what you see when searching in Solution Explorer), so I've added a resource that you can use to give it a thicker height if you want it to be like the progress bar in the `IVsThreadedWaitDialog`.
=> ProgressBar styles

.editorconfig, src/Community.VisualStudio.Toolkit.Shared/Options/BaseOptionModel.cs, src/Community.VisualStudio.Toolkit.UnitTests/OptionModelPropertyWrapperTests.cs, test/VSSDK.TestExtension/ToolWindows/ThemeWindow/ThemeWindow.cs, test/VSSDK.TestExtension/ToolWindows/ThemeWindow/ThemeWindowControlViewModel.cs
All current uses of `var` were updated to use explicit types.
=> Update .editorconfig to display errors when using the 'var' keyword instead of explicit types

src/Community.VisualStudio.Toolkit.Shared/Services.cs
The `<returns>` comment doesn't appear in intellisense, which makes it difficult to know what type to cast to for the service methods that return an `object`. I've moved that text into the `summary` element instead.
Before:
After:
=> Included the type to cast to in the summary comment to make it appear in intellisense

src/Community.VisualStudio.Toolkit.Shared/Solution/SolutionEvents.cs
Add the solutionFilename parameter for the OnBeforeOpenSolution event to the eventhandler. I need to know the path to the solution directory for this event and I believe this would be relevant for others that subscribe to this even too.
=> Add solutionFilename parameter to OnBeforeOpenSolution event.

src/Community.VisualStudio.Toolkit.Shared/Solution/PhysicalFolder.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/SolutionItem.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/SolutionItemType.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/VirtualFolder.cs, src/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems
Fixes #143. 
Added a `VirtualFolder` type to cover items in a solution like the `References` node of .NET Framework projects or the `Dependencies` node in SDK projects.
I've renamed `Folder` to `PhysicalFolder` to make it clear that it's a physical folder.
To fix the actual error in #143, the full path of a "virtual" or "unknown" item is not retrieved.
=> Support virtual folder types

src/Community.VisualStudio.Toolkit.Shared/Solution/PhysicalFolder.cs, src/Community.VisualStudio.Toolkit.Shared/Windows/Windows.cs
The existing method GetAllWindowsAsync() was only returning ToolWindows.
I have renamed that method to make this clear.
I have also added a method GetAllDocumentWindowsAsync() and finally added method with the original name GetAllWindowsAsync that returns both the ToolWindows and Document Windows.
=> Fix to Windows.GetAllWindowsAsync()

src/Community.VisualStudio.Toolkit.Shared/Solution/Solutions.cs, src/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems, src/Community.VisualStudio.Toolkit.Shared/Windows/SolutionExplorerWindow.cs, src/Community.VisualStudio.Toolkit.Shared/Windows/Windows.cs, test/VSSDK.TestExtension/Commands/CollapseSelectedItemsCommand.cs, test/VSSDK.TestExtension/Commands/EditSelectedItemLabelCommand.cs, test/VSSDK.TestExtension/Commands/ExpandSelectedItemsCommand.cs, test/VSSDK.TestExtension/Commands/SelectCurrentProjectCommand.cs, test/VSSDK.TestExtension/Commands/ToggleVsixManifestFilterCommand.cs, test/VSSDK.TestExtension/SolutionExplorer/VsixManifestFilterProvider.cs, test/VSSDK.TestExtension/VSCommandTable.cs, test/VSSDK.TestExtension/VSCommandTable.vsct, test/VSSDK.TestExtension/VSSDK.TestExtension.csproj
Fixes #98.
The `SolutionExplorerWindow` class provides access to the Solution Explorer tool window, and lets you do things like setting the selection, expanding and collapsing items and applying filters.
The window can be retrieved via the `VS.Windows.GetSolutionExplorerWindowAsync()` method.
As well as the methods to manipulate the Solution Explorer window, I've also exposed the underlying `IVsUIHierarchyWindow` and `IVsSolutionUIHierarchyWindow` objects (they're actually the same object), as well as the `IVsWindowFrame` that contains Solution Explorer, in case you need to do stuff that the `SolutionExplorerWindow` doesn't provide (in my use case I needed access to the `IVsWindowFrame` so that I could activate the window).
----
To assist with testing, and to provide a demonstration, I've …
=> Created a class for accessing and manipulating Solution Explorer

src/Community.VisualStudio.Toolkit.Shared/Projects/ProjectItemsEvents.cs, src/Community.VisualStudio.Toolkit.Shared/Windows/SolutionExplorerWindow.cs
There were a few compiler warnings showing up.
* Some missing XML documentation comments.
* Some missing calls to `ThreadHelper.ThrowIfNotOnUIThread()` that the analyzers were only detecting in the `C.VS.T.14.0` project.
=> Fixed compiler warnings

src/Community.VisualStudio.Toolkit.Shared/Windows/BaseToolWindow.cs, test/VSSDK.TestExtension/ToolWindows/RunnerWindowControl.xaml, test/VSSDK.TestExtension/ToolWindows/RunnerWindowControl.xaml.cs
Related to #149 
I've created the `BaseToolWindow.HideAsync()` method which can be used to hide a tool window.
Example:
```cs
await RunnerWindow.HideAsync();
```
=> Hide tool window

src/toolkit/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/IVsSolutionExtensions.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/ProjectStateFilter.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/SolutionItem.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/Solutions.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems
Fixes #191.
Changes:
* `ProjectStateFilter` is an enum that lets you choose between getting loaded, unloaded or all projects.
* `Solutions.GetAllProjectHierarchiesAsync` and `Solutions.GetAllProjectsAsync` now have an optional `ProjectStateFilter` property. The default is `Loaded` to match the previous behavior.
* `IVsSolutionExtensions.GetAllProjectHierarchies` also takes a `ProjectStateFilter`, which is converted to the corresponding `__VSENUMPROJFLAGS` value. The overload that takes a `__VSENUMPROJFLAGS` still exists.
* When getting the type for a `SolutionItem`, a "stub hierarchy" is treated as a project.
=> Improved unloaded project support

src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/SolutionItem.cs
I've also changed `Name` to return the `IVsHierarchy.CanonicalName` property rather than the `Text` property. I've added a `Text` property to get the hierarchy text.
The only difference I've been able to find between `CanonicalName` and `Text` is when a project is unloaded. For an unloaded project the `CanonicalName` will be "ProjectName", but the `Text` will be "ProjectName (unloaded)". 
I'm happy to revert the `Name` property back to returning the `IVsHierarcny.Text` if you think that would be better.
Fixes #198.
=> Made SolutionItem.Name and FullPath read-only

src/toolkit/Community.VisualStudio.Toolkit.Shared/Notifications/InfoBar.cs
`GetFrameFromIdentifierAsync` always returned null, so `CreateAsync(string, InfoBarModel)` would never find the `IVsWindowFrame` and therefore would never create the `InfoBar`.
=> Fixed showing an Info Bar on a window via the window GUID

demo/VSSDK.TestExtension/Commands/LoadSelectedProject.cs, demo/VSSDK.TestExtension/Commands/UnloadSelectedProject.cs, demo/VSSDK.TestExtension/VSCommandTable.cs, demo/VSSDK.TestExtension/VSCommandTable.vsct, demo/VSSDK.TestExtension/VSSDK.TestExtension.csproj, src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/Project.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/SolutionItem.cs
The `Project` class now has some additional methods to load and unload projects.
Load a project:
```cs
await project.LoadAsync();
```
Unload a project:
```cs
await project.UnloadAsync();
```
Check if a project is loaded:
```cs
if (project.IsLoaded) { }
```
Loading or unloading a project seems to dispose of the underlying `IVsHierarchy` object, so I've added an internal `SolutionItem.Update()` method that can be used to give the SolutionItem a new `IVsHierarchyItem`.
I've also added a couple of commands to the demo extension to demonstrate the new functionality.
=> Methods to load and unload projects

demo/VSSDK.TestExtension/Commands/SendMessageToRunnerWindowCommand.cs, demo/VSSDK.TestExtension/TestExtensionPackage.cs, demo/VSSDK.TestExtension/ToolWindows/RunnerWindow.cs, demo/VSSDK.TestExtension/ToolWindows/RunnerWindowControl.xaml, demo/VSSDK.TestExtension/ToolWindows/RunnerWindowControl.xaml.cs, demo/VSSDK.TestExtension/ToolWindows/RunnerWindowMessenger.cs, demo/VSSDK.TestExtension/VSCommandTable.cs, demo/VSSDK.TestExtension/VSCommandTable.vsct, demo/VSSDK.TestExtension/VSSDK.TestExtension.csproj
This demonstrates how to add a toolbar to a tool window. 
Documentation for how to do this _without_ using the toolkit can be found here: https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-toolbar-to-a-tool-window?view=vs-2022
Doing this _with_ the toolkit is basically the same. The toolbar is added by setting the `Toolbar` property on the internal `Pane` class of your tool window, because that's the class that inherits `ToolWindowPane`.
In this example, I've used a [`CommandPlacement`](https://docs.microsoft.com/en-us/visualstudio/extensibility/commandplacements-element?view=vs-2022) in the `.vsct` file to add the "Build Solution Async" command to the toolbar. The command also continues to appear in the "VSSDK Test Extension" menu. 
I've also added a new command to …
=> Example of adding a toolbar to a tool window

demo/VSSDK.TestExtension/Options/General.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/CVST001CastInteropServicesAnalyzer.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/CVST001CastInteropServicesCodeFixProvider.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/CVST002DialogPageShouldBeComVisibleAnalyzer.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/CVST002DialogPageShouldBeComVisibleCodeFixProvider.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/CodeFixProviderBase.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Diagnostics.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Resources.Designer.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Resources.resx, src/toolkit/Community.VisualStudio.Toolkit.Shared/Options/BaseOptionPage.cs, test/analyzers/Community.VisualStudio.Toolkit.Analyzers.UnitTests/Analyzers/CVST002DialogPageShouldBeComVisibleAnalyzerTests.cs
This pull request introduces a new code analyzer. This analyzer will detect classes that inherit from `DialogPage` that do not have the `[ComVisible(true)]` attribute. That attribute is required if the class `DialogPage` needs to support profiles (and there's no harm adding it if profiles don't need to be supported). Without it, exporting settings will silently ignore the settings defined in the `DialogPage`.
=> Analyzer for adding ComVisibleAttribute to DialogPage

src/toolkit/nuget/build/Community.VisualStudio.Toolkit.props
The toolkit includes an AssemblyInfo.cs file which ensures that the `ProvideCodeBase` attribute is applied to your extension. This file shows up in Solution Explorer, which is a bit confusing because it's not a file that you should edit.
I've added `Visible=false` metadata to the `Compile` item so that the file doesn't appear in Solution Explorer but is still included in the compilation.
=> Hide code files that are included from the NuGet package

src/toolkit/Community.VisualStudio.Toolkit.Shared/MEF/SameWordHighlighterBase.cs
My previous checkin caused the highlighted words to remain highlighted when the cursor moved to another word that was 'rejected'
=> Fore removal of highlighted words when word is "rejected"

src/toolkit/Community.VisualStudio.Toolkit.Shared/Commands/BaseCommand.cs
I am working on some changes to the `Community.VisualStudio.Toolkit.DependencyInjection` project that will allow registering commands in the DI container without the need to call the `BaseCommand.InitializeAsync` method.  I do however need to inherit from the `BaseCommand` and be able to set the `Package` and `Command` properties in the constructor.  This PR changes the setters on those public properties to `protected` so that inheritors can set them as well.
=> Make properties settable by inheritors.

src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/CVST002DialogPageShouldBeComVisibleAnalyzer.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/CVST002DialogPageShouldBeComVisibleCodeFixProvider.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/CVST003UseCorrectTypeInProvideOptionDialogPageAttributeAnalyzer.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/CVST003UseCorrectTypeInProvideOptionDialogPageAttributeCodeFixProvider.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/CVST004UseCorrectTypeInProvideProfileAttributeAnalyzer.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/CVST004UseCorrectTypeInProvideProfileAttributeCodeFixProvider.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/IncorrectProvidedTypeAnalyzerBase.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/IncorrectProvidedTypeCodeFixProviderBase.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/CodeFixProviderBase.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Community.VisualStudio.Toolkit.Analyzers.csproj, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Diagnostics.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Extensions.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/KnownTypeNames.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Resources.Designer.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Resources.resx, test/analyzers/Community.VisualStudio.Toolkit.Analyzers.UnitTests/Analyzers/CVST003UseCorrectTypeInProvideOptionDialogPageAttributeAnalyzerTests.cs, test/analyzers/Community.VisualStudio.Toolkit.Analyzers.UnitTests/Analyzers/CVST004UseCorrectTypeInProvideProfileAttributeAnalyzerTests.cs, test/analyzers/Community.VisualStudio.Toolkit.Analyzers.UnitTests/Helpers/TestBase.cs
Related to #279.
Using the wrong type in `ProvideOptionPageAttribute` seemed like a good candidate for a code analyzer to catch the problem early and to suggest a fix (where possible).
CVST003 will detect the wrong type being provided to `ProvideLanguageEditorOptionPageAttribute`, `ProvideOptionPageAttribute` and `ProvideToolboxPageAttribute` (they all expect a `DialogPage`)
CVST004 will detect the wrong type being provided to `ProvideProfileAttribute` (it expects an `IProfileManager`, which `DialogPage` implements).
Both diagnostics have a code fix that will suggest changing the type to a type that is nested within the type nested type that inherits/implements the correct type.  For example, give this:
```csharp
internal partial class OptionsProvider
{
[ComVisible(true)]
public class …
```
=> Code analyzer to check the type passed to ProvideOptionDialogPageAttribute and ProvideProfileAttribute

Community.VisualStudio.Toolkit.sln, src/toolkit/Community.VisualStudio.Toolkit.14.0/Community.VisualStudio.Toolkit.14.0.csproj, src/toolkit/Community.VisualStudio.Toolkit.15.0/Community.VisualStudio.Toolkit.15.0.csproj, src/toolkit/Community.VisualStudio.Toolkit.16.0/Community.VisualStudio.Toolkit.16.0.csproj, src/toolkit/Community.VisualStudio.Toolkit.17.0/Community.VisualStudio.Toolkit.17.0.csproj, src/toolkit/Directory.Build.props
There has been an issue with regards to using the project dropdown when working with files from the shared project:
It appears that we are unable to `Import` the shared project using a `.props` file. Each project must reference the shared project individually.
You can see the issue reported to MS [here](https://developercommunity.visualstudio.com/t/systemargumentoutofrangeexception-specified-argume-2/1427702?from=email&viewtype=all#T-N1654857).
=> Fixes an issue when trying to switch between projects for a shared file.

src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/Project.cs
This pull request updates Project.BuildAsync() to return the success flag from VS.Build.BuildProjectAsync().
=> Update Project.BuildAsync() to return success flag

src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/PhysicalFile.cs
Relates to #312.
I've added an overload to `PhysicalFile .TrySetAttributeAsync` where you can pass in an enum value instead of a string for the property name. This allows unusual attribute names (such as `{ItemType}`, which maps to the build action) to be easily specified.
I've also changed the `value` parameter to be an object, which allows `bool` or enum values to be passed in rather than having the caller convert the value to a string.
Examples:
```cs
await file.TrySetAttributeAsync(PhysicalFileAttribute.BuildAction, "None");
await file.TrySetAttributeAsync(PhysicalFileAttribute.CopyToOutputDirectory, CopyToOutputDirectory.Always);
await file.TrySetAttributeAsync(PhysicalFileAttribute.Visible, false);
await file.TrySetAttributeAsync(PhysicalFileAttribute.CustomToolNamespace, "Test"); …
```
=> Allowed PhysicalFile attributes to be set using known attribute names

demo/VSSDK.TestExtension/ToolWindows/ThemeWindow/CustomizedStylesDialog.xaml, demo/VSSDK.TestExtension/ToolWindows/ThemeWindow/CustomizedStylesDialog.xaml.cs, demo/VSSDK.TestExtension/ToolWindows/ThemeWindow/ThemeWindowControl.xaml, demo/VSSDK.TestExtension/ToolWindows/ThemeWindow/ThemeWindowControlViewModel.cs, demo/VSSDK.TestExtension/VSSDK.TestExtension.csproj, src/toolkit/Community.VisualStudio.Toolkit.Shared/Themes/InternalResourceKeys.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Themes/ThemeResources.xaml, src/toolkit/Community.VisualStudio.Toolkit.Shared/Themes/Themes.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Themes/ToolkitResourceKeys.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems, src/toolkit/Directory.Build.props
Fixed #135.
You can now extend the custom Visual Studio-themed styles. This required a few changes:
First, the resource dictionary needed to be compiled like any other XAML file by including it as a `Page`.
Doing that meant the `xmlns` attributes for the `Microsoft.VisualStudio.Shell.15.0` assembly could no longer be used. This is because in the v14 version of the toolkit, that assembly doesn't exist, and is actually `Microsoft.VisualStudio.Shell.14.0`. We were previously working around that by loading the XAML file from the embedded resources, doing some string replacement, and then parsing the file as a XAML file. I've solved this problem be creating an internal class called `InternalResourceKeys` in which we effectively alias the properties from `Microsoft.VisualStudio.Shell.xx.0` that …
=> Allow styles to be extended

Directory.Build.props, src/toolkit/Directory.Build.props
Fixes #322 
We needed to set the `UseWPF` build property to true.
> The UseWPF property controls whether or not to include references to WPF libraries. **This also alters the MSBuild pipeline to correctly process a WPF project and related files.**
https://docs.microsoft.com/en-US/dotnet/core/project-sdk/msbuild-props-desktop#usewpf
=> Set UseWPF build property to true for the toolkit projects.

demo/VSSDK.TestExtension/Commands/ListReferencesCommand.cs
The command was creating a new output pane each time it was run. Now it only creates a single output pane.
=> Ensured that only one "References" output pane is created by demo extension

demo/VSSDK.TestExtension/ToolWindows/RunnerWindow.cs, demo/VSSDK.TestExtension/ToolWindows/RunnerWindowControl.xaml.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/ToolkitPackage.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems, src/toolkit/Community.VisualStudio.Toolkit.Shared/Windows/BaseToolWindow.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Windows/IToolWindowPaneAware.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Windows/IToolWindowProvider.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Windows/ToolkitToolWindowPane.cs
Fixes #335.
This change allows a tool window to access the underlying `ToolWindowPane` object, which can then be used to access sited services.
To get access to the pane, you must make your pane inherit from `ToolkitToolWindowPane` instead of `ToolWindowPane`.
If you need to access the pane in your `BaseToolWindow<T>` class, override the `SetPane` method. If you need to access the pane in your tool window's content, make your content (for example, your `UserControl`) implement the `IToolWindowPaneAware` class.
After the tool window is created _and_ the `ToolWindowPane` has been initialized by Visual Studio, the `BaseToolWindow<T>.SetPane` and `IToolWindowPaneAware.SetPane` methods will be called.
=> Allowed a tool window or its content to get access to the ToolWindowPane

src/toolkit/Community.VisualStudio.Toolkit.Shared/Commands/BaseCommand.cs
Refactors the `CommandAttribute` check in `BaseCommand` to use pattern matching and use `GetCustomAttribute` instead of `GetCustomAttributes`. This results in cleaner and safer code, since `attr` will only be defined when not null.
=> Add cleaner command attribute check

src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/CVST005InitializeCommandsAnalyzer.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Analyzers/CVST005InitializeCommandsCodeFixProvider.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Diagnostics.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/KnownTypeNames.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Resources.Designer.cs, src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Resources.resx, test/analyzers/Community.VisualStudio.Toolkit.Analyzers.UnitTests/Analyzers/CVST005InitializeCommandsAnalyzerTests.cs
Related to https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/discussions/349#discussioncomment-2979674
This new code analyzer will detect when a command has not been initialized in the package's `InitializeAsync` method. The code fix works in one of two ways:
1. If any other command is being registered directly using `MyExistingCommand.Initialize(package)`, then the code fix will add a call to `MyUninitializedCommand.Initialize(package)` (where `MyUninitializedCommand` was the command that was not initialized).
2. If no other commands are being registered, the code fix will add a call to `this.RegisterCommandsAsync()`.
=> Created a code analyzer to detect commands that have not been initialized

src/toolkit/Community.VisualStudio.Toolkit.Shared/Notifications/InfoBar.cs
When subscribing to UI events for an `InfoBar`, the code is currently discarding the listener cookie, but this cookie should be used to later unsubscribe the event sink when closing the gold bar.
I also made some nit changes on the XAML docs, keeping consistency across the repo (e.g.: [Here](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/9c32305c83827d0bfd7c85777f9e79fc71e22c2b/src/toolkit/Community.VisualStudio.Toolkit.Shared/Commands/Commands.cs#L39) we use `<see langword="true" />` instead of `<c>true</c>`).
=> Using InfoBar listener cookie

src/toolkit/Community.VisualStudio.Toolkit.Shared/Shell/ShellEvents.cs
I'm not able to get the ShutdownStarted event to fire. Currently, it only triggers the event when __VSSPROPID6.VSSPROPID_ShutdownStarted is false. Checking the documentation (https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.__vsspropid6?view=visualstudiosdk-2022) it looks like the value should be true when Visual Studio is shutting down. With this change, it now triggers like I'd expect it to.
=> Fixed ShutdownStarted event never firing

demo/VSSDK.TestExtension/ToolWindows/ThemeWindow/ThemeWindowDemo.xaml, src/toolkit/Community.VisualStudio.Toolkit.Shared/Themes/ThemeResources.xaml, src/toolkit/Community.VisualStudio.Toolkit.Shared/Themes/ToolkitResourceKeys.cs
=> Added Visual Studio theme styles for RichTextBox

src/toolkit/Community.VisualStudio.Toolkit.Shared/Commands/BaseDynamicCommand.cs
If you have a dynamic command and at some point there are no dynamic items to display, then after that point the dynamic menu items will no longer appear, even when there are dynamic items to display.
This occurred because when there are no dynamic items, all of the menu items are hidden and disabled (otherwise you would end up with a single menu item that shouldn't be there). If at some point after that there are dynamic items again, the menu items would remain disabled and hidden unless the `BeforeQueryStatus` handler specifically set the menu item to be enabled and visible.
You can reproduce this bug in the test extension (without this fix, of course):
1. Open a solution with a few projects.
2. Open the _Extensions / VSSDK Test Extension / Edit Project File_ menu. You should see each …
=> Ensured that dynamic menu items are visible and enabled by default

src/toolkit/Community.VisualStudio.Toolkit.Shared/Commands/Commands.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Helpers/Disposable.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems
This PR changes `Commands.InterceptAsync` to return a `Task<IDisposable>`. When you dispose of the returned object, the command interceptor will be unregistered.
=> Allow command interceptors to be unregistered

src/toolkit/Community.VisualStudio.Toolkit.Shared/Windows/WindowFrame.cs
🚨 **This contains breaking changes** 🚨 
A few improvements to the `FrameShow` enum. Hopefully the breaking changes won't actually affect anyone. 🤞 
1. It was marked with the `[Flags]` attribute. The underlying `__FRAMESHOW` enum is not flagged.
2. There was a redundant `Unknown` member with a value of zero. That is equivalent to both `FRAMESHOW_Hidden` and `FRAMESHOW_WinHidden`. I've removed `Unknown`. **This is a breaking change.**
3. `FRAMESHOW_Hidden` is documented as being obsolete and has the same value as `FRAMESHOW_WinHidden`. I've removed `WinHidden` rather than `Hidden` because there is no corresponding `WinShown` value (but there is a `Shown` value). **This is a breaking change.**
4. I've added enum values for [`__FRAMESHOW2`](https://learn.microsoft.com/en-us/dotnet/api/microsof …
=> [Breaking Changes] Fix FrameShow enum

src/toolkit/nuget/build/imports/NewtonsoftJsonVersionCheck.targets
Fixes #434 
Two changes:
1. If the `Microsoft.VisualStudio.SDK` package is greater than the most recent 17.5 version (which means it is 17.6.36389 or above), then the `Newtonsoft.Json` version check is skipped because NuGet will raise warnings if the version of `Newtonsoft.Json` is higher than it should be.
2. Setting the build property `CheckNewtonsoftJsonVersion` to true will completely skip the version check, just in case you don't want it to run for whatever reason.
=> Skipped the Newtonsoft.Json version when using the newer VS SDK.

demo/VSSDK.TestExtension/MEF/HighlightWord.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/MEF/SameWordHighlighterBase.cs
Each TextView will register its events itself with the tagger from the textbuffer and when the textview is closed then the events are unregistered again.
The previous implementation was allocating way too many samewordhighlighters.
Also changed the color for the same word highlighters in the example code.
=> Make sure only a single SameWordHighlighter is attached to a textbuffer.

src/toolkit/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/AsyncPackageExtensions.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/ToolkitPackageExtensions.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems
Fixes #463.
`BaseToolWindow.Initialize` requires a `ToolkitPackage`, so the extension method should be on `ToolkitPackage`, not `AsyncPackage`.
=> Change RegisterToolWindows to be ToolkitPackage extension method.

src/toolkit/Community.VisualStudio.Toolkit.Shared/Helpers/OutputWindowPane.cs
As I need for my current project to write output into a single line, this would be a little enhancement. 
Added methods
- `void Write(string value);`
- `async Task WriteAsync(string value);`
Moved logic from `WriteLineAsync` to `WriteAsync`
=> Added Write without new line to OutputWindowPane

demo/VSSDK.TestExtension/ToolWindows/RunnerWindow.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Windows/ToolkitToolWindowPane.cs
This change allows a `ToolkitToolWindowPane` to get the underlying `WindowFrame` for the tool window. This is useful if you need to listen to events on the window frame to, for example, know when the tool window focused or closed.
=> Get a WindowFrame wrapper for a tool window

src/toolkit/Community.VisualStudio.Toolkit.Shared/FontsAndColors/BaseFontAndColorCategory.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/FontsAndColors/ConfiguredFont.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/FontsAndColors/ConfiguredFontAndColorSet.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/FontsAndColors/FontsAndColors.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/FontsAndColors/IFontAndColorChangeListener.cs
The font size specified in the `FontInfo` object is in points. WPF does not use points for font sizes, so the font size was always smaller than it should have been.
Fixes #523.
=> Calculated the correct font size for use in WPF.
