src/Community.VisualStudio.Toolkit.Shared/Commands/CommandBase.cs
=> Switch to main thread before calling IMenuCommandService.AddCommand

src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/ProjectExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/ProjectItemExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/Helpers/ProjectTypes.cs
Fixes #20 - Please review the names to see if any should be changed.  I basically just took them all from [here](https://www.codeproject.com/Reference/720512/List-of-Visual-Studio-Project-Type-GUIDs) and changed the names.  Many of them I don't even know personally so maybe others have better names/descriptions.  I really only have a question on the `SOLUTION_FOLDER` AND `SOLUTION_FOLDER_OTHER`.  I've detected for the `SOLUTION_FOLDER` before in an extension but have never encountered the `OTHER` one.
=> Added additional project types.

src/Community.VisualStudio.Toolkit.Shared/Helpers/ProjectTypes.cs
=> Added Extensibility project type

src/Community.VisualStudio.Toolkit.Shared/Build/Build.cs, src/Community.VisualStudio.Toolkit.Shared/Selection/Selection.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/Solution.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/SolutionItem.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/SolutionItemType.cs, src/Community.VisualStudio.Toolkit.Shared/VS.cs, src/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems
Renamed NodeType to SolutionItemType.
Separated to own code file.
Updated related summaries and variables.
=> Renamed NodeType to SolutionItemType

src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/IVsTextViewExtensions.cs
Fixed to nullable.  Missed this in PR #100.  Sorry about that.
=> Fixed IVsTextView nullable

src/Community.VisualStudio.Toolkit.Shared/Solution/SolutionItem.cs
=> Fixed misspelling

src/Community.VisualStudio.Toolkit.Shared/Build/BuildEvents.cs, src/Community.VisualStudio.Toolkit.Shared/Debugger/DebuggerEvents.cs, src/Community.VisualStudio.Toolkit.Shared/Notifications/StatusBar.cs, src/Community.VisualStudio.Toolkit.Shared/Selection/SelectionEvents.cs, src/Community.VisualStudio.Toolkit.Shared/Shell/Shell.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/File.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/Folder.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/SolutionEvents.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/SolutionFolder.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/SolutionItem.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/Solutions.cs, src/Community.VisualStudio.Toolkit.Shared/Windows/Windows.cs
- Fixed some spelling typos
- Corrected some comments
- Removed nullable IEnumerable<> return type from some methods that didn't need it
- Removed some nullable reference variable declarations when unneeded
=> Small fixes / improvements

src/Community.VisualStudio.Toolkit.Shared/Windows/WindowFrame.cs
Method appears to be calling wrong method.
=> Fixed WindowFrame IsVisibleAsync

src/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/AsyncPackageExtensions.cs, src/Community.VisualStudio.Toolkit.Shared/Options/BaseOptionModel.cs, test/VSSDK.TestExtension/ToolWindows/ThemeWindow/ThemeWindowControlViewModel.cs
Minor cleanup, removed some unneeded nullable variable declarations and merged some using statements.
=> Small refactoring

src/Community.VisualStudio.Toolkit.Shared/Build/BuildEvents.cs
Also fix solution event to report success/fail correctly.
Addresses #136
=> Enrich output from build done events to include success/fail

src/Community.VisualStudio.Toolkit.Shared/Build/BuildEvents.cs
Corrected typos/spelling of 'successful'
=> Fixed spelling typos

src/Community.VisualStudio.Toolkit.Shared/Helpers/ProjectTypes.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/PhysicalFile.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/PhysicalFolder.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/Project.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/SolutionFolder.cs, src/Community.VisualStudio.Toolkit.Shared/Solution/SolutionItem.cs, src/Community.VisualStudio.Toolkit.Shared/VSSDK.Helpers.Shared.projitems, src/Community.VisualStudio.Toolkit.Shared/Windows/WindowFrame.cs
Added GetDocumentAsync() on WindowsFrame to get the document opened in the frame
Also added the X# project type to the known ProjectTypes
=> Added GetDocumentAsync() on WindowsFrame and X# ProjectType

src/Community.VisualStudio.Toolkit.Shared/Helpers/ProvideGalleryFeedAttribute.cs
Updated the attribute message, was copied for another attribute
=> Update miss-copied comment

src/Community.VisualStudio.Toolkit.Shared/Build/Build.cs, test/VSSDK.TestExtension/Commands/BuildActiveProjectAsyncCommand.cs, test/VSSDK.TestExtension/Commands/BuildSolutionAsyncCommand.cs
=> Waited for the build to complete before returning from BuildProjectAsync and BuildSolutionAsync

src/toolkit/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/IVsHierarchyExtensions.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/IVsSolutionExtensions.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/SolutionItem.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/Solutions.cs
=> Used GetHierarchyItem instead of TryGetHierarchyItem

demo/VSSDK.TestExtension/TestExtensionPackage.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Build/BuildEvents.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/SolutionEvents.cs, src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/Solutions.cs
This fixes the following issues:
- incorrect ItemId was used to retrieve the project object
- Incorrect check for OnBeforeUnloadProject event handler
=> Fixes #205

src/toolkit/Community.VisualStudio.Toolkit.Shared/Notifications/InfoBar.cs
Fixes #231
```cs
InfoBar bar = await VS.InfoBar.CreateAsync(new InfoBarModel("Hello World!", KnownMonikers.Services, true));
await bar.TryShowInfoBarUIAsync();
```
=> Added the ability to show an Info Bar on the main window

README.md
Submitting PR for minor fixes in readme as mentioned in issue #225.
=> Minor fixes in Readme.md

README.md
For those interested in incorporating a DI container into their package I thought it would help to link to the [
Community.VisualStudio.Toolkit.DependencyInjection](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit.DependencyInjection) project on the README.
=> Update the README with a link to the 'Dependency Injection' project.

src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/SolutionFolder.cs
I have merged the suggested change from #251
=> Integrates suggested change from #251

src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/Project.cs
Related to #274.
Sample usage:
```csharp
// Existing method. Saves to the .csproj file.
await project.TrySetAttributeAsync("Foo", "InProject");
// New method. Saves to the .csproj file.
await project.TrySetAttributeAsync("Foo", "InProject2", ProjectStorageType.ProjectFile);  
// New method. Saves to the .csproj.user file.
await project.TrySetAttributeAsync("Foo", "InUser", ProjectStorageType.UserFile);
```
=> Allowed attributes to be stored in a project's user file

src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/Project.cs
We are renaming some of our company's build properties. For that it would be nice to be able to remove properties.
=> Add methods to remove attribute from Project

src/toolkit/Community.VisualStudio.Toolkit.Shared/Notifications/MessageBox.cs
=> ShowError should only have an OK button and not a Cancel button

src/toolkit/Community.VisualStudio.Toolkit.Shared/Windows/ToolkitToolWindowPane.cs
I forgot to finish one of the comments in #340.
=> Fixed the incomplete comment on ToolkitToolWindowPane

src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/Solutions.cs
Fixes the error described in #338.
=> Add open solution check when getting current solution

src/toolkit/Community.VisualStudio.Toolkit.Shared/MEF/SameWordHighlighterBase.cs
=> 1 letter identifiers can now also be highlighted

README.md
See https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#package-source-sections
> Note that the source URL for nuget.org is https://api.nuget.org/v3/index.json.
=> Updated the nuget.org package source URL in the readme

test/toolkit/Community.VisualStudio.Toolkit.UnitTests/Community.VisualStudio.Toolkit.UnitTests.csproj, test/toolkit/Community.VisualStudio.Toolkit.UnitTests/OptionModelPropertyWrapperTests.cs
See https://github.com/moq/moq/issues/1372.
=> Replaced Moq with NSubstitute

demo/VSSDK.TestExtension/Commands/SplitButtonCommand.cs, demo/VSSDK.TestExtension/VSCommandTable.cs, demo/VSSDK.TestExtension/VSCommandTable.vsct, demo/VSSDK.TestExtension/VSSDK.TestExtension.csproj
=> Demonstrate how to create a split button.

demo/VSSDK.TestExtension/Options/General.cs, demo/VSSDK.TestExtension/Options/RuntimeEnumProxy.cs, demo/VSSDK.TestExtension/Options/RuntimeEnumTypeConverter.cs, demo/VSSDK.TestExtension/VSSDK.TestExtension.csproj
=> Demonstrate how to treat a string property as an enum in Tools Options.
